require 'spec_helper'

# !!!!THIS FILE IS AUTOGENERATED.  DO NOT HAND EDIT!!!!

describe WampClient::Message do

  describe WampClient::Message::Hello do

    it 'creates the message object' do
      params = ['string',{ test: 1 }]
      object = WampClient::Message::Hello.new(*params)

      expect(object.realm).to eq('string')
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Hello)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [1,'string',{ test: 1 }]
      object = WampClient::Message::Hello.parse(params)

      expect(object.realm).to eq('string')
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Hello)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [1,'string',{ test: 1 }]
      object = WampClient::Message::Message.parse(params)

      expect(object.realm).to eq('string')
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Hello)).to eq(true)
    end

    it 'generates the payload' do
      params = ['string',{ test: 1 }]
      object = WampClient::Message::Hello.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(1)
      expect(payload[1]).to eq('string')
      expect(payload[2]).to eq({ test: 1 })
    end

  end

  describe WampClient::Message::Welcome do

    it 'creates the message object' do
      params = [123,{ test: 1 }]
      object = WampClient::Message::Welcome.new(*params)

      expect(object.session).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Welcome)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [2,123,{ test: 1 }]
      object = WampClient::Message::Welcome.parse(params)

      expect(object.session).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Welcome)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [2,123,{ test: 1 }]
      object = WampClient::Message::Message.parse(params)

      expect(object.session).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Welcome)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 }]
      object = WampClient::Message::Welcome.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(2)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
    end

  end

  describe WampClient::Message::Abort do

    it 'creates the message object' do
      params = [{ test: 1 },'string']
      object = WampClient::Message::Abort.new(*params)

      expect(object.details).to eq({ test: 1 })
      expect(object.reason).to eq('string')
      expect(object.is_a?(WampClient::Message::Abort)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [3,{ test: 1 },'string']
      object = WampClient::Message::Abort.parse(params)

      expect(object.details).to eq({ test: 1 })
      expect(object.reason).to eq('string')
      expect(object.is_a?(WampClient::Message::Abort)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [3,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.details).to eq({ test: 1 })
      expect(object.reason).to eq('string')
      expect(object.is_a?(WampClient::Message::Abort)).to eq(true)
    end

    it 'generates the payload' do
      params = [{ test: 1 },'string']
      object = WampClient::Message::Abort.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(3)
      expect(payload[1]).to eq({ test: 1 })
      expect(payload[2]).to eq('string')
    end

  end

  describe WampClient::Message::Goodbye do

    it 'creates the message object' do
      params = [{ test: 1 },'string']
      object = WampClient::Message::Goodbye.new(*params)

      expect(object.details).to eq({ test: 1 })
      expect(object.reason).to eq('string')
      expect(object.is_a?(WampClient::Message::Goodbye)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [6,{ test: 1 },'string']
      object = WampClient::Message::Goodbye.parse(params)

      expect(object.details).to eq({ test: 1 })
      expect(object.reason).to eq('string')
      expect(object.is_a?(WampClient::Message::Goodbye)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [6,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.details).to eq({ test: 1 })
      expect(object.reason).to eq('string')
      expect(object.is_a?(WampClient::Message::Goodbye)).to eq(true)
    end

    it 'generates the payload' do
      params = [{ test: 1 },'string']
      object = WampClient::Message::Goodbye.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(6)
      expect(payload[1]).to eq({ test: 1 })
      expect(payload[2]).to eq('string')
    end

  end

  describe WampClient::Message::Error do

    it 'creates the message object' do
      params = [123,123,{ test: 1 },'string']
      object = WampClient::Message::Error.new(*params)

      expect(object.request_type).to eq(123)
      expect(object.request_request).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.error).to eq('string')
      expect(object.is_a?(WampClient::Message::Error)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [8,123,123,{ test: 1 },'string']
      object = WampClient::Message::Error.parse(params)

      expect(object.request_type).to eq(123)
      expect(object.request_request).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.error).to eq('string')
      expect(object.is_a?(WampClient::Message::Error)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [8,123,123,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.request_type).to eq(123)
      expect(object.request_request).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.error).to eq('string')
      expect(object.is_a?(WampClient::Message::Error)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123,{ test: 1 },'string']
      object = WampClient::Message::Error.new(*params)
      payload = object.payload

      expect(payload.count).to eq(5)
      expect(payload[0]).to eq(8)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
      expect(payload[3]).to eq({ test: 1 })
      expect(payload[4]).to eq('string')
    end

    describe 'checks optional parameter arguments' do

      it 'creates the message object' do
        params = [123,123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Error.new(*params)

        expect(object.is_a?(WampClient::Message::Error)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [8,123,123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Error.parse(params)

        expect(object.is_a?(WampClient::Message::Error)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Error.new(*params)
        payload = object.payload

        expect(payload.count).to eq(6)
        expect(payload[0]).to eq(8)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq(123)
        expect(payload[3]).to eq({ test: 1 })
        expect(payload[4]).to eq('string')
        expect(payload[5]).to eq(['test'])
      end

    end

    describe 'checks optional parameter argumentskw' do

      it 'creates the message object' do
        params = [123,123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Error.new(*params)

        expect(object.is_a?(WampClient::Message::Error)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [8,123,123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Error.parse(params)

        expect(object.is_a?(WampClient::Message::Error)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Error.new(*params)
        payload = object.payload

        expect(payload.count).to eq(7)
        expect(payload[0]).to eq(8)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq(123)
        expect(payload[3]).to eq({ test: 1 })
        expect(payload[4]).to eq('string')
        expect(payload[5]).to eq(['test'])
        expect(payload[6]).to eq({ test: 1 })
      end

    end

  end

  describe WampClient::Message::Publish do

    it 'creates the message object' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Publish.new(*params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.topic).to eq('string')
      expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [16,123,{ test: 1 },'string']
      object = WampClient::Message::Publish.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.topic).to eq('string')
      expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [16,123,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.topic).to eq('string')
      expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Publish.new(*params)
      payload = object.payload

      expect(payload.count).to eq(4)
      expect(payload[0]).to eq(16)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
      expect(payload[3]).to eq('string')
    end

    describe 'checks optional parameter arguments' do

      it 'creates the message object' do
        params = [123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Publish.new(*params)

        expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [16,123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Publish.parse(params)

        expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Publish.new(*params)
        payload = object.payload

        expect(payload.count).to eq(5)
        expect(payload[0]).to eq(16)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq('string')
        expect(payload[4]).to eq(['test'])
      end

    end

    describe 'checks optional parameter argumentskw' do

      it 'creates the message object' do
        params = [123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Publish.new(*params)

        expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [16,123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Publish.parse(params)

        expect(object.is_a?(WampClient::Message::Publish)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Publish.new(*params)
        payload = object.payload

        expect(payload.count).to eq(6)
        expect(payload[0]).to eq(16)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq('string')
        expect(payload[4]).to eq(['test'])
        expect(payload[5]).to eq({ test: 1 })
      end

    end

  end

  describe WampClient::Message::Published do

    it 'creates the message object' do
      params = [123,123]
      object = WampClient::Message::Published.new(*params)

      expect(object.publish_request).to eq(123)
      expect(object.publication).to eq(123)
      expect(object.is_a?(WampClient::Message::Published)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [17,123,123]
      object = WampClient::Message::Published.parse(params)

      expect(object.publish_request).to eq(123)
      expect(object.publication).to eq(123)
      expect(object.is_a?(WampClient::Message::Published)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [17,123,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.publish_request).to eq(123)
      expect(object.publication).to eq(123)
      expect(object.is_a?(WampClient::Message::Published)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123]
      object = WampClient::Message::Published.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(17)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
    end

  end

  describe WampClient::Message::Subscribe do

    it 'creates the message object' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Subscribe.new(*params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.topic).to eq('string')
      expect(object.is_a?(WampClient::Message::Subscribe)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [32,123,{ test: 1 },'string']
      object = WampClient::Message::Subscribe.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.topic).to eq('string')
      expect(object.is_a?(WampClient::Message::Subscribe)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [32,123,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.topic).to eq('string')
      expect(object.is_a?(WampClient::Message::Subscribe)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Subscribe.new(*params)
      payload = object.payload

      expect(payload.count).to eq(4)
      expect(payload[0]).to eq(32)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
      expect(payload[3]).to eq('string')
    end

  end

  describe WampClient::Message::Subscribed do

    it 'creates the message object' do
      params = [123,123]
      object = WampClient::Message::Subscribed.new(*params)

      expect(object.subscribe_request).to eq(123)
      expect(object.subscription).to eq(123)
      expect(object.is_a?(WampClient::Message::Subscribed)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [33,123,123]
      object = WampClient::Message::Subscribed.parse(params)

      expect(object.subscribe_request).to eq(123)
      expect(object.subscription).to eq(123)
      expect(object.is_a?(WampClient::Message::Subscribed)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [33,123,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.subscribe_request).to eq(123)
      expect(object.subscription).to eq(123)
      expect(object.is_a?(WampClient::Message::Subscribed)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123]
      object = WampClient::Message::Subscribed.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(33)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
    end

  end

  describe WampClient::Message::Unsubscribe do

    it 'creates the message object' do
      params = [123,123]
      object = WampClient::Message::Unsubscribe.new(*params)

      expect(object.request).to eq(123)
      expect(object.subscribed_subscription).to eq(123)
      expect(object.is_a?(WampClient::Message::Unsubscribe)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [34,123,123]
      object = WampClient::Message::Unsubscribe.parse(params)

      expect(object.request).to eq(123)
      expect(object.subscribed_subscription).to eq(123)
      expect(object.is_a?(WampClient::Message::Unsubscribe)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [34,123,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.subscribed_subscription).to eq(123)
      expect(object.is_a?(WampClient::Message::Unsubscribe)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123]
      object = WampClient::Message::Unsubscribe.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(34)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
    end

  end

  describe WampClient::Message::Unsubscribed do

    it 'creates the message object' do
      params = [123]
      object = WampClient::Message::Unsubscribed.new(*params)

      expect(object.unsubscribe_request).to eq(123)
      expect(object.is_a?(WampClient::Message::Unsubscribed)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [35,123]
      object = WampClient::Message::Unsubscribed.parse(params)

      expect(object.unsubscribe_request).to eq(123)
      expect(object.is_a?(WampClient::Message::Unsubscribed)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [35,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.unsubscribe_request).to eq(123)
      expect(object.is_a?(WampClient::Message::Unsubscribed)).to eq(true)
    end

    it 'generates the payload' do
      params = [123]
      object = WampClient::Message::Unsubscribed.new(*params)
      payload = object.payload

      expect(payload.count).to eq(2)
      expect(payload[0]).to eq(35)
      expect(payload[1]).to eq(123)
    end

  end

  describe WampClient::Message::Event do

    it 'creates the message object' do
      params = [123,123,{ test: 1 }]
      object = WampClient::Message::Event.new(*params)

      expect(object.subscribed_subscription).to eq(123)
      expect(object.published_publication).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Event)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [36,123,123,{ test: 1 }]
      object = WampClient::Message::Event.parse(params)

      expect(object.subscribed_subscription).to eq(123)
      expect(object.published_publication).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Event)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [36,123,123,{ test: 1 }]
      object = WampClient::Message::Message.parse(params)

      expect(object.subscribed_subscription).to eq(123)
      expect(object.published_publication).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Event)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123,{ test: 1 }]
      object = WampClient::Message::Event.new(*params)
      payload = object.payload

      expect(payload.count).to eq(4)
      expect(payload[0]).to eq(36)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
      expect(payload[3]).to eq({ test: 1 })
    end

    describe 'checks optional parameter publish_arguments' do

      it 'creates the message object' do
        params = [123,123,{ test: 1 },['test']]
        object = WampClient::Message::Event.new(*params)

        expect(object.is_a?(WampClient::Message::Event)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [36,123,123,{ test: 1 },['test']]
        object = WampClient::Message::Event.parse(params)

        expect(object.is_a?(WampClient::Message::Event)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,123,{ test: 1 },['test']]
        object = WampClient::Message::Event.new(*params)
        payload = object.payload

        expect(payload.count).to eq(5)
        expect(payload[0]).to eq(36)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq(123)
        expect(payload[3]).to eq({ test: 1 })
        expect(payload[4]).to eq(['test'])
      end

    end

    describe 'checks optional parameter publish_argumentskw' do

      it 'creates the message object' do
        params = [123,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Event.new(*params)

        expect(object.is_a?(WampClient::Message::Event)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [36,123,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Event.parse(params)

        expect(object.is_a?(WampClient::Message::Event)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Event.new(*params)
        payload = object.payload

        expect(payload.count).to eq(6)
        expect(payload[0]).to eq(36)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq(123)
        expect(payload[3]).to eq({ test: 1 })
        expect(payload[4]).to eq(['test'])
        expect(payload[5]).to eq({ test: 1 })
      end

    end

  end

  describe WampClient::Message::Call do

    it 'creates the message object' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Call.new(*params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.procedure).to eq('string')
      expect(object.is_a?(WampClient::Message::Call)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [48,123,{ test: 1 },'string']
      object = WampClient::Message::Call.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.procedure).to eq('string')
      expect(object.is_a?(WampClient::Message::Call)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [48,123,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.procedure).to eq('string')
      expect(object.is_a?(WampClient::Message::Call)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Call.new(*params)
      payload = object.payload

      expect(payload.count).to eq(4)
      expect(payload[0]).to eq(48)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
      expect(payload[3]).to eq('string')
    end

    describe 'checks optional parameter arguments' do

      it 'creates the message object' do
        params = [123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Call.new(*params)

        expect(object.is_a?(WampClient::Message::Call)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [48,123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Call.parse(params)

        expect(object.is_a?(WampClient::Message::Call)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },'string',['test']]
        object = WampClient::Message::Call.new(*params)
        payload = object.payload

        expect(payload.count).to eq(5)
        expect(payload[0]).to eq(48)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq('string')
        expect(payload[4]).to eq(['test'])
      end

    end

    describe 'checks optional parameter argumentskw' do

      it 'creates the message object' do
        params = [123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Call.new(*params)

        expect(object.is_a?(WampClient::Message::Call)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [48,123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Call.parse(params)

        expect(object.is_a?(WampClient::Message::Call)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },'string',['test'],{ test: 1 }]
        object = WampClient::Message::Call.new(*params)
        payload = object.payload

        expect(payload.count).to eq(6)
        expect(payload[0]).to eq(48)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq('string')
        expect(payload[4]).to eq(['test'])
        expect(payload[5]).to eq({ test: 1 })
      end

    end

  end

  describe WampClient::Message::Result do

    it 'creates the message object' do
      params = [123,{ test: 1 }]
      object = WampClient::Message::Result.new(*params)

      expect(object.call_request).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Result)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [50,123,{ test: 1 }]
      object = WampClient::Message::Result.parse(params)

      expect(object.call_request).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Result)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [50,123,{ test: 1 }]
      object = WampClient::Message::Message.parse(params)

      expect(object.call_request).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Result)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 }]
      object = WampClient::Message::Result.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(50)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
    end

    describe 'checks optional parameter yield_arguments' do

      it 'creates the message object' do
        params = [123,{ test: 1 },['test']]
        object = WampClient::Message::Result.new(*params)

        expect(object.is_a?(WampClient::Message::Result)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [50,123,{ test: 1 },['test']]
        object = WampClient::Message::Result.parse(params)

        expect(object.is_a?(WampClient::Message::Result)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },['test']]
        object = WampClient::Message::Result.new(*params)
        payload = object.payload

        expect(payload.count).to eq(4)
        expect(payload[0]).to eq(50)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq(['test'])
      end

    end

    describe 'checks optional parameter yield_argumentskw' do

      it 'creates the message object' do
        params = [123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Result.new(*params)

        expect(object.is_a?(WampClient::Message::Result)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [50,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Result.parse(params)

        expect(object.is_a?(WampClient::Message::Result)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Result.new(*params)
        payload = object.payload

        expect(payload.count).to eq(5)
        expect(payload[0]).to eq(50)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq(['test'])
        expect(payload[4]).to eq({ test: 1 })
      end

    end

  end

  describe WampClient::Message::Register do

    it 'creates the message object' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Register.new(*params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.procedure).to eq('string')
      expect(object.is_a?(WampClient::Message::Register)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [64,123,{ test: 1 },'string']
      object = WampClient::Message::Register.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.procedure).to eq('string')
      expect(object.is_a?(WampClient::Message::Register)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [64,123,{ test: 1 },'string']
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.procedure).to eq('string')
      expect(object.is_a?(WampClient::Message::Register)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 },'string']
      object = WampClient::Message::Register.new(*params)
      payload = object.payload

      expect(payload.count).to eq(4)
      expect(payload[0]).to eq(64)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
      expect(payload[3]).to eq('string')
    end

  end

  describe WampClient::Message::Registered do

    it 'creates the message object' do
      params = [123,123]
      object = WampClient::Message::Registered.new(*params)

      expect(object.register_request).to eq(123)
      expect(object.registration).to eq(123)
      expect(object.is_a?(WampClient::Message::Registered)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [65,123,123]
      object = WampClient::Message::Registered.parse(params)

      expect(object.register_request).to eq(123)
      expect(object.registration).to eq(123)
      expect(object.is_a?(WampClient::Message::Registered)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [65,123,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.register_request).to eq(123)
      expect(object.registration).to eq(123)
      expect(object.is_a?(WampClient::Message::Registered)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123]
      object = WampClient::Message::Registered.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(65)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
    end

  end

  describe WampClient::Message::Unregister do

    it 'creates the message object' do
      params = [123,123]
      object = WampClient::Message::Unregister.new(*params)

      expect(object.request).to eq(123)
      expect(object.registered_registration).to eq(123)
      expect(object.is_a?(WampClient::Message::Unregister)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [66,123,123]
      object = WampClient::Message::Unregister.parse(params)

      expect(object.request).to eq(123)
      expect(object.registered_registration).to eq(123)
      expect(object.is_a?(WampClient::Message::Unregister)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [66,123,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.registered_registration).to eq(123)
      expect(object.is_a?(WampClient::Message::Unregister)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123]
      object = WampClient::Message::Unregister.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(66)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
    end

  end

  describe WampClient::Message::Unregistered do

    it 'creates the message object' do
      params = [123]
      object = WampClient::Message::Unregistered.new(*params)

      expect(object.unregister_request).to eq(123)
      expect(object.is_a?(WampClient::Message::Unregistered)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [67,123]
      object = WampClient::Message::Unregistered.parse(params)

      expect(object.unregister_request).to eq(123)
      expect(object.is_a?(WampClient::Message::Unregistered)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [67,123]
      object = WampClient::Message::Message.parse(params)

      expect(object.unregister_request).to eq(123)
      expect(object.is_a?(WampClient::Message::Unregistered)).to eq(true)
    end

    it 'generates the payload' do
      params = [123]
      object = WampClient::Message::Unregistered.new(*params)
      payload = object.payload

      expect(payload.count).to eq(2)
      expect(payload[0]).to eq(67)
      expect(payload[1]).to eq(123)
    end

  end

  describe WampClient::Message::Invocation do

    it 'creates the message object' do
      params = [123,123,{ test: 1 }]
      object = WampClient::Message::Invocation.new(*params)

      expect(object.request).to eq(123)
      expect(object.registered_registration).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [68,123,123,{ test: 1 }]
      object = WampClient::Message::Invocation.parse(params)

      expect(object.request).to eq(123)
      expect(object.registered_registration).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [68,123,123,{ test: 1 }]
      object = WampClient::Message::Message.parse(params)

      expect(object.request).to eq(123)
      expect(object.registered_registration).to eq(123)
      expect(object.details).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,123,{ test: 1 }]
      object = WampClient::Message::Invocation.new(*params)
      payload = object.payload

      expect(payload.count).to eq(4)
      expect(payload[0]).to eq(68)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq(123)
      expect(payload[3]).to eq({ test: 1 })
    end

    describe 'checks optional parameter call_arguments' do

      it 'creates the message object' do
        params = [123,123,{ test: 1 },['test']]
        object = WampClient::Message::Invocation.new(*params)

        expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [68,123,123,{ test: 1 },['test']]
        object = WampClient::Message::Invocation.parse(params)

        expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,123,{ test: 1 },['test']]
        object = WampClient::Message::Invocation.new(*params)
        payload = object.payload

        expect(payload.count).to eq(5)
        expect(payload[0]).to eq(68)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq(123)
        expect(payload[3]).to eq({ test: 1 })
        expect(payload[4]).to eq(['test'])
      end

    end

    describe 'checks optional parameter call_argumentskw' do

      it 'creates the message object' do
        params = [123,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Invocation.new(*params)

        expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [68,123,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Invocation.parse(params)

        expect(object.is_a?(WampClient::Message::Invocation)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Invocation.new(*params)
        payload = object.payload

        expect(payload.count).to eq(6)
        expect(payload[0]).to eq(68)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq(123)
        expect(payload[3]).to eq({ test: 1 })
        expect(payload[4]).to eq(['test'])
        expect(payload[5]).to eq({ test: 1 })
      end

    end

  end

  describe WampClient::Message::Yield do

    it 'creates the message object' do
      params = [123,{ test: 1 }]
      object = WampClient::Message::Yield.new(*params)

      expect(object.invocation_request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
    end

    it 'parses the message and creates an object' do
      params = [70,123,{ test: 1 }]
      object = WampClient::Message::Yield.parse(params)

      expect(object.invocation_request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
    end

    it 'globally parses the message and creates an object' do
      params = [70,123,{ test: 1 }]
      object = WampClient::Message::Message.parse(params)

      expect(object.invocation_request).to eq(123)
      expect(object.options).to eq({ test: 1 })
      expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
    end

    it 'generates the payload' do
      params = [123,{ test: 1 }]
      object = WampClient::Message::Yield.new(*params)
      payload = object.payload

      expect(payload.count).to eq(3)
      expect(payload[0]).to eq(70)
      expect(payload[1]).to eq(123)
      expect(payload[2]).to eq({ test: 1 })
    end

    describe 'checks optional parameter arguments' do

      it 'creates the message object' do
        params = [123,{ test: 1 },['test']]
        object = WampClient::Message::Yield.new(*params)

        expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [70,123,{ test: 1 },['test']]
        object = WampClient::Message::Yield.parse(params)

        expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },['test']]
        object = WampClient::Message::Yield.new(*params)
        payload = object.payload

        expect(payload.count).to eq(4)
        expect(payload[0]).to eq(70)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq(['test'])
      end

    end

    describe 'checks optional parameter argumentskw' do

      it 'creates the message object' do
        params = [123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Yield.new(*params)

        expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
      end

      it 'parses the message and creates an object' do
        params = [70,123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Yield.parse(params)

        expect(object.is_a?(WampClient::Message::Yield)).to eq(true)
      end

      it 'generates the payload' do
        params = [123,{ test: 1 },['test'],{ test: 1 }]
        object = WampClient::Message::Yield.new(*params)
        payload = object.payload

        expect(payload.count).to eq(5)
        expect(payload[0]).to eq(70)
        expect(payload[1]).to eq(123)
        expect(payload[2]).to eq({ test: 1 })
        expect(payload[3]).to eq(['test'])
        expect(payload[4]).to eq({ test: 1 })
      end

    end

  end

end