require 'wamp_client/check'

# !!!!THIS FILE IS AUTOGENERATED.  DO NOT HAND EDIT!!!!

module WampClient
  module Message

    module Types
      HELLO = 1
      WELCOME = 2
      ABORT = 3
      GOODBYE = 6
      ERROR = 8
      PUBLISH = 16
      PUBLISHED = 17
      SUBSCRIBE = 32
      SUBSCRIBED = 33
      UNSUBSCRIBE = 34
      UNSUBSCRIBED = 35
      EVENT = 36
      CALL = 48
      RESULT = 50
      REGISTER = 64
      REGISTERED = 65
      UNREGISTER = 66
      UNREGISTERED = 67
      INVOCATION = 68
      YIELD = 70
    end

    class Base
      include WampClient::Check

      def payload
        []
      end

      # @param params [Array]
      def self.parse(params)
        object = nil
        if params[0] == Types::HELLO
          object = WampClient::Message::Hello.parse(params)
        elsif params[0] == Types::WELCOME
          object = WampClient::Message::Welcome.parse(params)
        elsif params[0] == Types::ABORT
          object = WampClient::Message::Abort.parse(params)
        elsif params[0] == Types::GOODBYE
          object = WampClient::Message::Goodbye.parse(params)
        elsif params[0] == Types::ERROR
          object = WampClient::Message::Error.parse(params)
        elsif params[0] == Types::PUBLISH
          object = WampClient::Message::Publish.parse(params)
        elsif params[0] == Types::PUBLISHED
          object = WampClient::Message::Published.parse(params)
        elsif params[0] == Types::SUBSCRIBE
          object = WampClient::Message::Subscribe.parse(params)
        elsif params[0] == Types::SUBSCRIBED
          object = WampClient::Message::Subscribed.parse(params)
        elsif params[0] == Types::UNSUBSCRIBE
          object = WampClient::Message::Unsubscribe.parse(params)
        elsif params[0] == Types::UNSUBSCRIBED
          object = WampClient::Message::Unsubscribed.parse(params)
        elsif params[0] == Types::EVENT
          object = WampClient::Message::Event.parse(params)
        elsif params[0] == Types::CALL
          object = WampClient::Message::Call.parse(params)
        elsif params[0] == Types::RESULT
          object = WampClient::Message::Result.parse(params)
        elsif params[0] == Types::REGISTER
          object = WampClient::Message::Register.parse(params)
        elsif params[0] == Types::REGISTERED
          object = WampClient::Message::Registered.parse(params)
        elsif params[0] == Types::UNREGISTER
          object = WampClient::Message::Unregister.parse(params)
        elsif params[0] == Types::UNREGISTERED
          object = WampClient::Message::Unregistered.parse(params)
        elsif params[0] == Types::INVOCATION
          object = WampClient::Message::Invocation.parse(params)
        elsif params[0] == Types::YIELD
          object = WampClient::Message::Yield.parse(params)
        end

        object
      end

    end

    # Hello
    # Sent by a Client to initiate opening of a WAMP session to a Router attaching to a Realm.
    # Formats:
    #   [HELLO, Realm|uri, Details|dict]
    class Hello < Base
      @realm
      @details

      def initialize(realm, details)

        self.class.check_uri('realm', realm)
        self.class.check_dict('details', details)

        @realm = realm
        @details = details

      end

      def self.type
        Types::HELLO
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@realm)
        payload.push(@details)

        payload
      end

      def realm
        @realm
      end

      def details
        @details || {}
      end

    end

    # Welcome
    # Sent by a Router to accept a Client.  The WAMP session is now open.
    # Formats:
    #   [WELCOME, Session|id, Details|dict]
    class Welcome < Base
      @session
      @details

      def initialize(session, details)

        self.class.check_id('session', session)
        self.class.check_dict('details', details)

        @session = session
        @details = details

      end

      def self.type
        Types::WELCOME
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@session)
        payload.push(@details)

        payload
      end

      def session
        @session
      end

      def details
        @details || {}
      end

    end

    # Abort
    # Sent by a Peer*to abort the opening of a WAMP session.  No response is expected.
    # Formats:
    #   [ABORT, Details|dict, Reason|uri]
    class Abort < Base
      @details
      @reason

      def initialize(details, reason)

        self.class.check_dict('details', details)
        self.class.check_uri('reason', reason)

        @details = details
        @reason = reason

      end

      def self.type
        Types::ABORT
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@details)
        payload.push(@reason)

        payload
      end

      def details
        @details || {}
      end

      def reason
        @reason
      end

    end

    # Goodbye
    # Sent by a Peer to close a previously opened WAMP session.  Must be echo'ed by the receiving Peer.
    # Formats:
    #   [GOODBYE, Details|dict, Reason|uri]
    class Goodbye < Base
      @details
      @reason

      def initialize(details, reason)

        self.class.check_dict('details', details)
        self.class.check_uri('reason', reason)

        @details = details
        @reason = reason

      end

      def self.type
        Types::GOODBYE
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@details)
        payload.push(@reason)

        payload
      end

      def details
        @details || {}
      end

      def reason
        @reason
      end

    end

    # Error
    # Error reply sent by a Peer as an error response to different kinds of requests.
    # Formats:
    #   [ERROR, REQUEST.Type|int, REQUEST.Request|id, Details|dict, Error|uri]
    #   [ERROR, REQUEST.Type|int, REQUEST.Request|id, Details|dict, Error|uri, Arguments|list]
    #   [ERROR, REQUEST.Type|int, REQUEST.Request|id, Details|dict, Error|uri, Arguments|list, ArgumentsKw|dict]
    class Error < Base
      @request_type
      @request_request
      @details
      @error
      @arguments
      @argumentskw

      def initialize(request_type, request_request, details, error, arguments=nil, argumentskw=nil)

        self.class.check_int('request_type', request_type)
        self.class.check_id('request_request', request_request)
        self.class.check_dict('details', details)
        self.class.check_uri('error', error)
        self.class.check_list('arguments', arguments, true)
        self.class.check_dict('argumentskw', argumentskw, true)

        @request_type = request_type
        @request_request = request_request
        @details = details
        @error = error
        @arguments = arguments
        @argumentskw = argumentskw

      end

      def self.type
        Types::ERROR
      end

      def self.parse(params)

        self.check_gte('params list', 5, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request_type)
        payload.push(@request_request)
        payload.push(@details)
        payload.push(@error)

        return payload if @arguments.nil?
        payload.push(@arguments)

        return payload if @argumentskw.nil?
        payload.push(@argumentskw)

        payload
      end

      def request_type
        @request_type
      end

      def request_request
        @request_request
      end

      def details
        @details || {}
      end

      def error
        @error
      end

      def arguments
        @arguments || []
      end

      def argumentskw
        @argumentskw || {}
      end

    end

    # Publish
    # Sent by a Publisher to a Broker to publish an event.
    # Formats:
    #   [PUBLISH, Request|id, Options|dict, Topic|uri]
    #   [PUBLISH, Request|id, Options|dict, Topic|uri, Arguments|list]
    #   [PUBLISH, Request|id, Options|dict, Topic|uri, Arguments|list, ArgumentsKw|dict]
    class Publish < Base
      @request
      @options
      @topic
      @arguments
      @argumentskw

      def initialize(request, options, topic, arguments=nil, argumentskw=nil)

        self.class.check_id('request', request)
        self.class.check_dict('options', options)
        self.class.check_uri('topic', topic)
        self.class.check_list('arguments', arguments, true)
        self.class.check_dict('argumentskw', argumentskw, true)

        @request = request
        @options = options
        @topic = topic
        @arguments = arguments
        @argumentskw = argumentskw

      end

      def self.type
        Types::PUBLISH
      end

      def self.parse(params)

        self.check_gte('params list', 4, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@options)
        payload.push(@topic)

        return payload if @arguments.nil?
        payload.push(@arguments)

        return payload if @argumentskw.nil?
        payload.push(@argumentskw)

        payload
      end

      def request
        @request
      end

      def options
        @options || {}
      end

      def topic
        @topic
      end

      def arguments
        @arguments || []
      end

      def argumentskw
        @argumentskw || {}
      end

    end

    # Published
    # Acknowledge sent by a Broker to a Publisher for acknowledged publications.
    # Formats:
    #   [PUBLISHED, PUBLISH.Request|id, Publication|id]
    class Published < Base
      @publish_request
      @publication

      def initialize(publish_request, publication)

        self.class.check_id('publish_request', publish_request)
        self.class.check_id('publication', publication)

        @publish_request = publish_request
        @publication = publication

      end

      def self.type
        Types::PUBLISHED
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@publish_request)
        payload.push(@publication)

        payload
      end

      def publish_request
        @publish_request
      end

      def publication
        @publication
      end

    end

    # Subscribe
    # Subscribe request sent by a Subscriber to a Broker to subscribe to a topic.
    # Formats:
    #   [SUBSCRIBE, Request|id, Options|dict, Topic|uri]
    class Subscribe < Base
      @request
      @options
      @topic

      def initialize(request, options, topic)

        self.class.check_id('request', request)
        self.class.check_dict('options', options)
        self.class.check_uri('topic', topic)

        @request = request
        @options = options
        @topic = topic

      end

      def self.type
        Types::SUBSCRIBE
      end

      def self.parse(params)

        self.check_gte('params list', 4, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@options)
        payload.push(@topic)

        payload
      end

      def request
        @request
      end

      def options
        @options || {}
      end

      def topic
        @topic
      end

    end

    # Subscribed
    # Acknowledge sent by a Broker to a Subscriber to acknowledge a subscription.
    # Formats:
    #   [SUBSCRIBED, SUBSCRIBE.Request|id, Subscription|id]
    class Subscribed < Base
      @subscribe_request
      @subscription

      def initialize(subscribe_request, subscription)

        self.class.check_id('subscribe_request', subscribe_request)
        self.class.check_id('subscription', subscription)

        @subscribe_request = subscribe_request
        @subscription = subscription

      end

      def self.type
        Types::SUBSCRIBED
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@subscribe_request)
        payload.push(@subscription)

        payload
      end

      def subscribe_request
        @subscribe_request
      end

      def subscription
        @subscription
      end

    end

    # Unsubscribe
    # Unsubscribe request sent by a Subscriber to a Broker to unsubscribe a subscription.
    # Formats:
    #   [UNSUBSCRIBE, Request|id, SUBSCRIBED.Subscription|id]
    class Unsubscribe < Base
      @request
      @subscribed_subscription

      def initialize(request, subscribed_subscription)

        self.class.check_id('request', request)
        self.class.check_id('subscribed_subscription', subscribed_subscription)

        @request = request
        @subscribed_subscription = subscribed_subscription

      end

      def self.type
        Types::UNSUBSCRIBE
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@subscribed_subscription)

        payload
      end

      def request
        @request
      end

      def subscribed_subscription
        @subscribed_subscription
      end

    end

    # Unsubscribed
    # Acknowledge sent by a Broker to a Subscriber to acknowledge unsubscription.
    # Formats:
    #   [UNSUBSCRIBED, UNSUBSCRIBE.Request|id]
    class Unsubscribed < Base
      @unsubscribe_request

      def initialize(unsubscribe_request)

        self.class.check_id('unsubscribe_request', unsubscribe_request)

        @unsubscribe_request = unsubscribe_request

      end

      def self.type
        Types::UNSUBSCRIBED
      end

      def self.parse(params)

        self.check_gte('params list', 2, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@unsubscribe_request)

        payload
      end

      def unsubscribe_request
        @unsubscribe_request
      end

    end

    # Event
    # Event dispatched by Broker to Subscribers for subscriptions the event was matching.
    # Formats:
    #   [EVENT, SUBSCRIBED.Subscription|id, PUBLISHED.Publication|id, Details|dict]
    #   [EVENT, SUBSCRIBED.Subscription|id, PUBLISHED.Publication|id, Details|dict, PUBLISH.Arguments|list]
    #   [EVENT, SUBSCRIBED.Subscription|id, PUBLISHED.Publication|id, Details|dict, PUBLISH.Arguments|list, PUBLISH.ArgumentsKw|dict]
    class Event < Base
      @subscribed_subscription
      @published_publication
      @details
      @publish_arguments
      @publish_argumentskw

      def initialize(subscribed_subscription, published_publication, details, publish_arguments=nil, publish_argumentskw=nil)

        self.class.check_id('subscribed_subscription', subscribed_subscription)
        self.class.check_id('published_publication', published_publication)
        self.class.check_dict('details', details)
        self.class.check_list('publish_arguments', publish_arguments, true)
        self.class.check_dict('publish_argumentskw', publish_argumentskw, true)

        @subscribed_subscription = subscribed_subscription
        @published_publication = published_publication
        @details = details
        @publish_arguments = publish_arguments
        @publish_argumentskw = publish_argumentskw

      end

      def self.type
        Types::EVENT
      end

      def self.parse(params)

        self.check_gte('params list', 4, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@subscribed_subscription)
        payload.push(@published_publication)
        payload.push(@details)

        return payload if @publish_arguments.nil?
        payload.push(@publish_arguments)

        return payload if @publish_argumentskw.nil?
        payload.push(@publish_argumentskw)

        payload
      end

      def subscribed_subscription
        @subscribed_subscription
      end

      def published_publication
        @published_publication
      end

      def details
        @details || {}
      end

      def publish_arguments
        @publish_arguments || []
      end

      def publish_argumentskw
        @publish_argumentskw || {}
      end

    end

    # Call
    # Call as originally issued by the _Caller_ to the _Dealer_.
    # Formats:
    #   [CALL, Request|id, Options|dict, Procedure|uri]
    #   [CALL, Request|id, Options|dict, Procedure|uri, Arguments|list]
    #   [CALL, Request|id, Options|dict, Procedure|uri, Arguments|list, ArgumentsKw|dict]
    class Call < Base
      @request
      @options
      @procedure
      @arguments
      @argumentskw

      def initialize(request, options, procedure, arguments=nil, argumentskw=nil)

        self.class.check_id('request', request)
        self.class.check_dict('options', options)
        self.class.check_uri('procedure', procedure)
        self.class.check_list('arguments', arguments, true)
        self.class.check_dict('argumentskw', argumentskw, true)

        @request = request
        @options = options
        @procedure = procedure
        @arguments = arguments
        @argumentskw = argumentskw

      end

      def self.type
        Types::CALL
      end

      def self.parse(params)

        self.check_gte('params list', 4, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@options)
        payload.push(@procedure)

        return payload if @arguments.nil?
        payload.push(@arguments)

        return payload if @argumentskw.nil?
        payload.push(@argumentskw)

        payload
      end

      def request
        @request
      end

      def options
        @options || {}
      end

      def procedure
        @procedure
      end

      def arguments
        @arguments || []
      end

      def argumentskw
        @argumentskw || {}
      end

    end

    # Result
    # Result of a call as returned by _Dealer_ to _Caller_.
    # Formats:
    #   [RESULT, CALL.Request|id, Details|dict]
    #   [RESULT, CALL.Request|id, Details|dict, YIELD.Arguments|list]
    #   [RESULT, CALL.Request|id, Details|dict, YIELD.Arguments|list, YIELD.ArgumentsKw|dict]
    class Result < Base
      @call_request
      @details
      @yield_arguments
      @yield_argumentskw

      def initialize(call_request, details, yield_arguments=nil, yield_argumentskw=nil)

        self.class.check_id('call_request', call_request)
        self.class.check_dict('details', details)
        self.class.check_list('yield_arguments', yield_arguments, true)
        self.class.check_dict('yield_argumentskw', yield_argumentskw, true)

        @call_request = call_request
        @details = details
        @yield_arguments = yield_arguments
        @yield_argumentskw = yield_argumentskw

      end

      def self.type
        Types::RESULT
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@call_request)
        payload.push(@details)

        return payload if @yield_arguments.nil?
        payload.push(@yield_arguments)

        return payload if @yield_argumentskw.nil?
        payload.push(@yield_argumentskw)

        payload
      end

      def call_request
        @call_request
      end

      def details
        @details || {}
      end

      def yield_arguments
        @yield_arguments || []
      end

      def yield_argumentskw
        @yield_argumentskw || {}
      end

    end

    # Register
    # A _Callees_ request to register an endpoint at a _Dealer_.
    # Formats:
    #   [REGISTER, Request|id, Options|dict, Procedure|uri]
    class Register < Base
      @request
      @options
      @procedure

      def initialize(request, options, procedure)

        self.class.check_id('request', request)
        self.class.check_dict('options', options)
        self.class.check_uri('procedure', procedure)

        @request = request
        @options = options
        @procedure = procedure

      end

      def self.type
        Types::REGISTER
      end

      def self.parse(params)

        self.check_gte('params list', 4, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@options)
        payload.push(@procedure)

        payload
      end

      def request
        @request
      end

      def options
        @options || {}
      end

      def procedure
        @procedure
      end

    end

    # Registered
    # Acknowledge sent by a _Dealer_ to a _Callee_ for successful registration.
    # Formats:
    #   [REGISTERED, REGISTER.Request|id, Registration|id]
    class Registered < Base
      @register_request
      @registration

      def initialize(register_request, registration)

        self.class.check_id('register_request', register_request)
        self.class.check_id('registration', registration)

        @register_request = register_request
        @registration = registration

      end

      def self.type
        Types::REGISTERED
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@register_request)
        payload.push(@registration)

        payload
      end

      def register_request
        @register_request
      end

      def registration
        @registration
      end

    end

    # Unregister
    # A _Callees_ request to unregister a previously established registration.
    # Formats:
    #   [UNREGISTER, Request|id, REGISTERED.Registration|id]
    class Unregister < Base
      @request
      @registered_registration

      def initialize(request, registered_registration)

        self.class.check_id('request', request)
        self.class.check_id('registered_registration', registered_registration)

        @request = request
        @registered_registration = registered_registration

      end

      def self.type
        Types::UNREGISTER
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@registered_registration)

        payload
      end

      def request
        @request
      end

      def registered_registration
        @registered_registration
      end

    end

    # Unregistered
    # Acknowledge sent by a _Dealer_ to a _Callee_ for successful unregistration.
    # Formats:
    #   [UNREGISTERED, UNREGISTER.Request|id]
    class Unregistered < Base
      @unregister_request

      def initialize(unregister_request)

        self.class.check_id('unregister_request', unregister_request)

        @unregister_request = unregister_request

      end

      def self.type
        Types::UNREGISTERED
      end

      def self.parse(params)

        self.check_gte('params list', 2, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@unregister_request)

        payload
      end

      def unregister_request
        @unregister_request
      end

    end

    # Invocation
    # Actual invocation of an endpoint sent by _Dealer_ to a _Callee_.
    # Formats:
    #   [INVOCATION, Request|id, REGISTERED.Registration|id, Details|dict]
    #   [INVOCATION, Request|id, REGISTERED.Registration|id, Details|dict, CALL.Arguments|list]
    #   [INVOCATION, Request|id, REGISTERED.Registration|id, Details|dict, CALL.Arguments|list, CALL.ArgumentsKw|dict]
    class Invocation < Base
      @request
      @registered_registration
      @details
      @call_arguments
      @call_argumentskw

      def initialize(request, registered_registration, details, call_arguments=nil, call_argumentskw=nil)

        self.class.check_id('request', request)
        self.class.check_id('registered_registration', registered_registration)
        self.class.check_dict('details', details)
        self.class.check_list('call_arguments', call_arguments, true)
        self.class.check_dict('call_argumentskw', call_argumentskw, true)

        @request = request
        @registered_registration = registered_registration
        @details = details
        @call_arguments = call_arguments
        @call_argumentskw = call_argumentskw

      end

      def self.type
        Types::INVOCATION
      end

      def self.parse(params)

        self.check_gte('params list', 4, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@request)
        payload.push(@registered_registration)
        payload.push(@details)

        return payload if @call_arguments.nil?
        payload.push(@call_arguments)

        return payload if @call_argumentskw.nil?
        payload.push(@call_argumentskw)

        payload
      end

      def request
        @request
      end

      def registered_registration
        @registered_registration
      end

      def details
        @details || {}
      end

      def call_arguments
        @call_arguments || []
      end

      def call_argumentskw
        @call_argumentskw || {}
      end

    end

    # Yield
    # Actual yield from an endpoint sent by a _Callee_ to _Dealer_.
    # Formats:
    #   [YIELD, INVOCATION.Request|id, Options|dict]
    #   [YIELD, INVOCATION.Request|id, Options|dict, Arguments|list]
    #   [YIELD, INVOCATION.Request|id, Options|dict, Arguments|list, ArgumentsKw|dict]
    class Yield < Base
      @invocation_request
      @options
      @arguments
      @argumentskw

      def initialize(invocation_request, options, arguments=nil, argumentskw=nil)

        self.class.check_id('invocation_request', invocation_request)
        self.class.check_dict('options', options)
        self.class.check_list('arguments', arguments, true)
        self.class.check_dict('argumentskw', argumentskw, true)

        @invocation_request = invocation_request
        @options = options
        @arguments = arguments
        @argumentskw = argumentskw

      end

      def self.type
        Types::YIELD
      end

      def self.parse(params)

        self.check_gte('params list', 3, params.count)
        self.check_equal('message type', self.type, params[0])

        params.shift
        self.new(*params)

      end

      def payload
        payload = [self.class.type]
        payload.push(@invocation_request)
        payload.push(@options)

        return payload if @arguments.nil?
        payload.push(@arguments)

        return payload if @argumentskw.nil?
        payload.push(@argumentskw)

        payload
      end

      def invocation_request
        @invocation_request
      end

      def options
        @options || {}
      end

      def arguments
        @arguments || []
      end

      def argumentskw
        @argumentskw || {}
      end

    end

  end
end